[2025-01-17T10:58:58.450+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:58:58.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T10:58:58.470+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:58.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:58:58.559+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:58:58.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T10:58:58.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:58:58.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.176 seconds
[2025-01-17T10:59:29.154+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:59:29.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T10:59:29.163+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:29.162+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:59:29.197+0000] {logging_mixin.py:190} INFO - [2025-01-17T10:59:29.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T10:59:29.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T10:59:29.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.089 seconds
[2025-01-17T11:00:00.116+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:00.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:00:00.120+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:00.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:00.134+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:00.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:00:00.135+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:00.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T11:00:30.984+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:30.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:00:30.990+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:30.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:31.019+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:00:31.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:00:31.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:00:31.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.087 seconds
[2025-01-17T11:01:01.723+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:01.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:01:01.725+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:01.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:01.740+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:01.736+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:01:01.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:01.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.038 seconds
[2025-01-17T11:01:31.908+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:31.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:01:31.911+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:31.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:31.927+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:01:31.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:01:31.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:01:31.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T11:02:01.988+0000] {processor.py:186} INFO - Started process (PID=474) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:01.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:02:01.992+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:01.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:02.005+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:02.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:02:02.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:02.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:02:32.601+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:32.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:02:32.604+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:32.604+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:32.623+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:02:32.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:02:32.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:02:32.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:03:03.172+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:03.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:03:03.175+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:03.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:03.199+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:03.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:03:03.200+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:03.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:03:33.325+0000] {processor.py:186} INFO - Started process (PID=676) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:33.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:03:33.330+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:33.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:33.348+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:03:33.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:03:33.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:03:33.381+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.063 seconds
[2025-01-17T11:04:03.569+0000] {processor.py:186} INFO - Started process (PID=743) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:03.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:04:03.572+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:03.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:03.585+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:03.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:04:03.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:03.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.046 seconds
[2025-01-17T11:04:33.918+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:33.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:04:33.921+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:33.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:33.934+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:04:33.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:04:33.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:04:33.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:05:04.057+0000] {processor.py:186} INFO - Started process (PID=877) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:04.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:05:04.059+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:04.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:04.074+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:04.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:05:04.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:04.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2025-01-17T11:05:34.888+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:34.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:05:34.891+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:34.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:34.903+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:05:34.900+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:05:34.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:05:34.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:06:05.189+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:05.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:06:05.192+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:05.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:05.206+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:05.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:06:05.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:05.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:06:35.756+0000] {processor.py:186} INFO - Started process (PID=1078) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:35.757+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:06:35.759+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:35.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:35.771+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:06:35.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:06:35.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:06:35.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:07:05.936+0000] {processor.py:186} INFO - Started process (PID=1145) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:05.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:07:05.941+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:05.940+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:05.955+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:05.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:07:05.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:05.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.045 seconds
[2025-01-17T11:07:36.351+0000] {processor.py:186} INFO - Started process (PID=1212) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:36.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:07:36.355+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:36.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:36.369+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:07:36.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:07:36.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:07:36.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T11:08:06.592+0000] {processor.py:186} INFO - Started process (PID=1279) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:06.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:08:06.596+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:06.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:06.608+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:06.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:08:06.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:06.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:08:37.371+0000] {processor.py:186} INFO - Started process (PID=1346) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:37.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:08:37.375+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:37.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:37.389+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:08:37.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:08:37.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:08:37.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.053 seconds
[2025-01-17T11:09:07.663+0000] {processor.py:186} INFO - Started process (PID=1413) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:07.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:09:07.667+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:07.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:07.679+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:07.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:09:07.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:07.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:09:38.486+0000] {processor.py:186} INFO - Started process (PID=1480) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:38.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:09:38.488+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:38.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:38.501+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:09:38.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:09:38.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:09:38.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.044 seconds
[2025-01-17T11:10:09.141+0000] {processor.py:186} INFO - Started process (PID=1546) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:09.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:10:09.144+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:09.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:09.160+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:09.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:10:09.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:09.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.044 seconds
[2025-01-17T11:10:39.696+0000] {processor.py:186} INFO - Started process (PID=1612) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:39.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:10:39.698+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:39.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:39.711+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:10:39.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:10:39.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:10:39.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:11:10.472+0000] {processor.py:186} INFO - Started process (PID=1677) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:10.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:11:10.474+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:10.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:10.486+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:10.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:11:10.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:10.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:11:40.960+0000] {processor.py:186} INFO - Started process (PID=1742) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:40.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:11:40.962+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:40.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:40.975+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:11:40.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:11:40.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:11:41.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:12:11.297+0000] {processor.py:186} INFO - Started process (PID=1807) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:11.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:12:11.299+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:11.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:11.312+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:11.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:12:11.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:11.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:12:41.815+0000] {processor.py:186} INFO - Started process (PID=1872) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:41.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:12:41.817+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:41.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:41.830+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:12:41.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:12:41.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:12:41.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.052 seconds
[2025-01-17T11:13:12.371+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:12.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:13:12.374+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:12.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:12.390+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:12.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:13:12.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:12.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.044 seconds
[2025-01-17T11:13:42.505+0000] {processor.py:186} INFO - Started process (PID=2002) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:42.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:13:42.507+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:42.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:42.520+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:13:42.516+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:13:42.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:13:42.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.038 seconds
[2025-01-17T11:14:12.820+0000] {processor.py:186} INFO - Started process (PID=2068) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:12.821+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:14:12.822+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:12.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:12.834+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:12.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:14:12.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:12.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.046 seconds
[2025-01-17T11:14:43.100+0000] {processor.py:186} INFO - Started process (PID=2134) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:43.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:14:43.102+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:43.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:43.116+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:14:43.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:14:43.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:14:43.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.036 seconds
[2025-01-17T11:15:14.293+0000] {processor.py:186} INFO - Started process (PID=2200) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:14.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:15:14.295+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:14.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:14.308+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:14.305+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:15:14.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:14.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:15:44.474+0000] {processor.py:186} INFO - Started process (PID=2250) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:44.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:15:44.476+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:44.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:44.488+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:15:44.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:15:44.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:15:44.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.036 seconds
[2025-01-17T11:16:14.826+0000] {processor.py:186} INFO - Started process (PID=2308) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:14.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:16:14.830+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:14.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:14.842+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:14.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:16:14.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:14.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T11:16:45.039+0000] {processor.py:186} INFO - Started process (PID=2371) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:45.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:16:45.041+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:45.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:45.057+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:16:45.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:16:45.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:16:45.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.046 seconds
[2025-01-17T11:17:15.548+0000] {processor.py:186} INFO - Started process (PID=2437) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:15.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:17:15.551+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:15.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:15.565+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:15.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:17:15.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:15.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:17:46.134+0000] {processor.py:186} INFO - Started process (PID=2503) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:46.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:17:46.136+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:46.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:46.152+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:17:46.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:17:46.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:17:46.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:18:16.823+0000] {processor.py:186} INFO - Started process (PID=2569) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:16.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:18:16.826+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:16.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:16.843+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:16.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:18:16.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:16.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.056 seconds
[2025-01-17T11:18:47.301+0000] {processor.py:186} INFO - Started process (PID=2636) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:47.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:18:47.304+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:47.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:47.317+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:18:47.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:18:47.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:18:47.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:19:18.153+0000] {processor.py:186} INFO - Started process (PID=2702) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:18.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:19:18.155+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:18.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:18.167+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:18.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:19:18.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:18.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.036 seconds
[2025-01-17T11:19:48.557+0000] {processor.py:186} INFO - Started process (PID=2768) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:48.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:19:48.560+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:48.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:48.572+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:19:48.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:19:48.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:19:48.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:20:19.288+0000] {processor.py:186} INFO - Started process (PID=2834) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:19.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:20:19.291+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:19.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:19.304+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:19.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:20:19.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:19.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:20:49.435+0000] {processor.py:186} INFO - Started process (PID=2900) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:49.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:20:49.438+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:49.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:49.451+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:20:49.447+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:20:49.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:20:49.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:21:20.019+0000] {processor.py:186} INFO - Started process (PID=2966) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:20.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:21:20.023+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:20.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:20.045+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:20.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:21:20.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:20.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.058 seconds
[2025-01-17T11:21:50.361+0000] {processor.py:186} INFO - Started process (PID=3032) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:50.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:21:50.363+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:50.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:50.378+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:21:50.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:21:50.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:21:50.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.051 seconds
[2025-01-17T11:22:20.592+0000] {processor.py:186} INFO - Started process (PID=3099) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:20.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:22:20.594+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:20.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:20.608+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:20.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:22:20.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:20.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:22:51.319+0000] {processor.py:186} INFO - Started process (PID=3165) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:51.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:22:51.322+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:51.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:51.335+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:22:51.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:22:51.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:22:51.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2025-01-17T11:23:21.838+0000] {processor.py:186} INFO - Started process (PID=3231) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:21.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:23:21.841+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:21.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:21.856+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:21.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:23:21.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:21.873+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T11:23:51.957+0000] {processor.py:186} INFO - Started process (PID=3297) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:51.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:23:51.959+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:51.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:51.971+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:23:51.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:23:51.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:23:52.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:24:22.622+0000] {processor.py:186} INFO - Started process (PID=3363) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:22.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:24:22.624+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:22.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:22.637+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:22.633+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:24:22.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:22.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T11:24:53.528+0000] {processor.py:186} INFO - Started process (PID=3429) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:53.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:24:53.540+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:53.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:53.564+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:24:53.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:24:53.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:24:53.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.077 seconds
[2025-01-17T11:25:23.983+0000] {processor.py:186} INFO - Started process (PID=3495) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:23.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:25:23.985+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:23.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:23.998+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:23.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:25:23.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:24.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:25:54.345+0000] {processor.py:186} INFO - Started process (PID=3561) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:54.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:25:54.347+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:54.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:54.362+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:25:54.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:25:54.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:25:54.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.050 seconds
[2025-01-17T11:26:24.647+0000] {processor.py:186} INFO - Started process (PID=3627) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:24.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:26:24.649+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:24.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:24.660+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:24.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:26:24.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:24.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:26:54.746+0000] {processor.py:186} INFO - Started process (PID=3692) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:54.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:26:54.749+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:54.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:54.765+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:26:54.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:26:54.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:26:54.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.053 seconds
[2025-01-17T11:27:24.982+0000] {processor.py:186} INFO - Started process (PID=3758) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:24.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:27:24.984+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:24.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:24.999+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:24.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:27:25.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:25.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:27:55.536+0000] {processor.py:186} INFO - Started process (PID=3824) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:55.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:27:55.538+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:55.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:55.551+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:27:55.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:27:55.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:27:55.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T11:28:26.554+0000] {processor.py:186} INFO - Started process (PID=3890) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:26.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:28:26.556+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:26.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:26.570+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:26.566+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:28:26.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:26.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T11:28:56.927+0000] {processor.py:186} INFO - Started process (PID=3956) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:56.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:28:56.930+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:56.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:56.951+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:28:56.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:28:56.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:28:56.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.070 seconds
[2025-01-17T11:29:27.581+0000] {processor.py:186} INFO - Started process (PID=4023) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:27.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:29:27.583+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:27.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:27.596+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:27.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:29:27.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:27.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:29:58.083+0000] {processor.py:186} INFO - Started process (PID=4089) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:58.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:29:58.086+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:58.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:58.098+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:29:58.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:29:58.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:29:58.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.046 seconds
[2025-01-17T11:40:52.419+0000] {processor.py:186} INFO - Started process (PID=4148) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:40:52.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:40:52.422+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:40:52.441+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:40:52.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:40:52.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:40:52.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.053 seconds
[2025-01-17T11:41:23.054+0000] {processor.py:186} INFO - Started process (PID=4210) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:23.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:41:23.056+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:23.070+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:23.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:41:23.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:23.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:41:53.393+0000] {processor.py:186} INFO - Started process (PID=4276) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:53.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:41:53.395+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:53.408+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:41:53.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:41:53.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:41:53.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:42:23.758+0000] {processor.py:186} INFO - Started process (PID=4342) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:23.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:42:23.760+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:23.774+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:23.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:42:23.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:23.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:42:54.477+0000] {processor.py:186} INFO - Started process (PID=4408) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:54.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:42:54.479+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:54.503+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:42:54.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:42:54.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:42:54.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T11:43:24.815+0000] {processor.py:186} INFO - Started process (PID=4474) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:24.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:43:24.817+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:24.830+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:24.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:43:24.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:24.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T11:43:55.271+0000] {processor.py:186} INFO - Started process (PID=4540) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:55.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:43:55.273+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:55.286+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:43:55.282+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:43:55.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:43:55.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:44:25.766+0000] {processor.py:186} INFO - Started process (PID=4606) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:25.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:44:25.768+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:25.781+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:25.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:44:25.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:25.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:44:55.982+0000] {processor.py:186} INFO - Started process (PID=4672) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:55.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:44:55.984+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:55.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:55.997+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:44:55.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:44:55.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:44:56.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2025-01-17T11:45:26.665+0000] {processor.py:186} INFO - Started process (PID=4738) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:26.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:45:26.667+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:26.680+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:26.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:45:26.681+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:26.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:45:57.234+0000] {processor.py:186} INFO - Started process (PID=4804) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:57.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:45:57.236+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:57.248+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:45:57.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:45:57.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:45:57.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:46:27.394+0000] {processor.py:186} INFO - Started process (PID=4870) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:27.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:46:27.397+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:27.417+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:27.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:46:27.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:27.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.054 seconds
[2025-01-17T11:46:57.771+0000] {processor.py:186} INFO - Started process (PID=4936) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:57.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:46:57.775+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:57.790+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:46:57.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:46:57.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:46:57.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:47:28.161+0000] {processor.py:186} INFO - Started process (PID=5002) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:28.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:47:28.163+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:28.176+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:28.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:47:28.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:28.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T11:47:58.329+0000] {processor.py:186} INFO - Started process (PID=5068) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:58.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:47:58.331+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:58.344+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:47:58.341+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:47:58.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:47:58.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T11:48:28.683+0000] {processor.py:186} INFO - Started process (PID=5134) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:28.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:48:28.686+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:28.698+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:28.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:48:28.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:28.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T11:48:58.995+0000] {processor.py:186} INFO - Started process (PID=5200) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:58.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:48:58.997+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:58.997+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:59.014+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:48:59.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:48:59.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:48:59.040+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.051 seconds
[2025-01-17T11:49:29.468+0000] {processor.py:186} INFO - Started process (PID=5266) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:49:29.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T11:49:29.482+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:49:29.530+0000] {logging_mixin.py:190} INFO - [2025-01-17T11:49:29.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T11:49:29.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T11:49:29.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.126 seconds
[2025-01-17T12:03:42.939+0000] {processor.py:186} INFO - Started process (PID=5280) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:03:42.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:03:42.942+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:42.941+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:03:42.960+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:03:42.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:03:42.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:03:42.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T12:04:13.103+0000] {processor.py:186} INFO - Started process (PID=5344) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:13.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:04:13.105+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:13.119+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:13.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:04:13.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:13.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.048 seconds
[2025-01-17T12:04:43.986+0000] {processor.py:186} INFO - Started process (PID=5410) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:43.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:04:43.988+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:43.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:44.000+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:04:43.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:04:44.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:04:44.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T12:05:14.162+0000] {processor.py:186} INFO - Started process (PID=5476) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:14.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:05:14.164+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:14.179+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:14.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:05:14.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:14.194+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T12:05:44.485+0000] {processor.py:186} INFO - Started process (PID=5542) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:44.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:05:44.488+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:44.502+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:05:44.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:05:44.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:05:44.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.038 seconds
[2025-01-17T12:06:14.761+0000] {processor.py:186} INFO - Started process (PID=5608) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:14.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:06:14.764+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:14.777+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:14.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:06:14.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:14.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T12:06:44.865+0000] {processor.py:186} INFO - Started process (PID=5674) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:44.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:06:44.868+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:44.881+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:06:44.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:06:44.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:06:44.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:07:15.323+0000] {processor.py:186} INFO - Started process (PID=5740) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:15.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:07:15.325+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:15.339+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:15.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:07:15.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:15.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:07:46.112+0000] {processor.py:186} INFO - Started process (PID=5806) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:46.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:07:46.115+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:46.127+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:07:46.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:07:46.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:07:46.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.035 seconds
[2025-01-17T12:08:16.982+0000] {processor.py:186} INFO - Started process (PID=5872) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:16.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:08:16.984+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:16.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:16.997+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:16.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:08:16.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:17.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:08:48.001+0000] {processor.py:186} INFO - Started process (PID=5938) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:48.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:08:48.003+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:48.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:48.017+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:08:48.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:08:48.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:08:48.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T12:09:19.020+0000] {processor.py:186} INFO - Started process (PID=6010) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:19.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:09:19.022+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:19.034+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:19.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:09:19.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:19.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T12:09:49.931+0000] {processor.py:186} INFO - Started process (PID=6076) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:49.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:09:49.933+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:49.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:49.947+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:09:49.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:09:49.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:09:49.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T12:10:20.416+0000] {processor.py:186} INFO - Started process (PID=6142) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:20.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:10:20.418+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:20.432+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:20.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:10:20.433+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:20.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:10:50.835+0000] {processor.py:186} INFO - Started process (PID=6208) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:50.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:10:50.838+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:50.856+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:10:50.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:10:50.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:10:50.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2025-01-17T12:11:21.303+0000] {processor.py:186} INFO - Started process (PID=6274) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:21.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:11:21.305+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:21.318+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:21.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:11:21.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:21.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:11:51.642+0000] {processor.py:186} INFO - Started process (PID=6340) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:51.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:11:51.644+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:51.660+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:11:51.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:11:51.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:11:51.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T12:12:22.372+0000] {processor.py:186} INFO - Started process (PID=6406) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:22.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:12:22.374+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:22.387+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:22.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:12:22.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:22.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2025-01-17T12:12:53.440+0000] {processor.py:186} INFO - Started process (PID=6472) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:53.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:12:53.441+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:53.455+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:12:53.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:12:53.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:12:53.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2025-01-17T12:13:24.150+0000] {processor.py:186} INFO - Started process (PID=6538) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:24.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:13:24.155+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:24.183+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:24.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:13:24.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:24.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.095 seconds
[2025-01-17T12:13:55.187+0000] {processor.py:186} INFO - Started process (PID=6604) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:55.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:13:55.190+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:55.203+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:13:55.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:13:55.204+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:13:55.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T12:14:25.303+0000] {processor.py:186} INFO - Started process (PID=6670) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:25.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:14:25.305+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:25.319+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:25.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:14:25.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:25.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T12:14:55.586+0000] {processor.py:186} INFO - Started process (PID=6736) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:55.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:14:55.588+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:55.600+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:14:55.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:14:55.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:14:55.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2025-01-17T12:15:26.659+0000] {processor.py:186} INFO - Started process (PID=6802) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:26.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:15:26.661+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:26.675+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:26.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:15:26.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:26.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.045 seconds
[2025-01-17T12:15:56.967+0000] {processor.py:186} INFO - Started process (PID=6868) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:56.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:15:56.969+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:56.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:56.982+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:15:56.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:15:56.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:15:57.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.043 seconds
[2025-01-17T12:16:27.837+0000] {processor.py:186} INFO - Started process (PID=6934) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:27.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:16:27.838+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:27.853+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:27.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:16:27.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:27.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.037 seconds
[2025-01-17T12:16:58.496+0000] {processor.py:186} INFO - Started process (PID=7000) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:58.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:16:58.499+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:58.514+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:16:58.510+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:16:58.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:16:58.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T12:17:29.276+0000] {processor.py:186} INFO - Started process (PID=7066) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:17:29.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:17:29.278+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:17:29.300+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:17:29.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:17:29.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:17:29.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2025-01-17T12:18:00.181+0000] {processor.py:186} INFO - Started process (PID=7132) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:00.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:18:00.183+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:00.198+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:00.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:18:00.199+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:00.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2025-01-17T12:18:30.560+0000] {processor.py:186} INFO - Started process (PID=7198) to work on /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:30.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2025-01-17T12:18:30.568+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:30.619+0000] {logging_mixin.py:190} INFO - [2025-01-17T12:18:30.603+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 593, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'test project' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2025-01-17T12:18:30.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2025-01-17T12:18:30.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.159 seconds
